language: ruby
rvm:
- 2.0.0
- 1.9.3
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: k+TlT27maEpHn0qR4i9o5zJjV01OH6WyXnWAoSvB5YbPBy2OU6kgHdl6R07AbfIvuVkI04xYY61PVh7m5PwuMRgRF3gnr3ZYLX6OvCHMvBvMLU8Yt55KYEdzGox3ySaVEBJasoJwL3boP57sLQObb4s0A0Zym2p8yvit+7nG0sgCXuM4IrMClWIdGG7FKFh1fWW4E5iAcok7jHlY9I8NzUbTyRuUpc8S51FcreSSndT4D4UC2yaJP0Q8GSqflMuSX8vKMQ9jJMK7IrryLWDradNFKxf2Hd6ACNO0T2opTg5whh/tpUV3Hxr+kNTcy73fgxc5ipqULkdbW0DCvS3jrk9pCEEuY/W8a5Z2ViipeBEEFtGYt4+ixxZ+7rt1mRvuoXsie2T6oq66ofG5vnA0ATmjkQwW0KCiify0ah0AqgmQlGExCvC30T9ECOCn1jrsL9Ogbt9J6XDgkK1T8jBszFZ5+FvrgU6Q9uVre5kP6SXlU/Tr6t/DU1AnJXdGgQQHlL/SgAEdlTUhWcp+mu+fte45E0QGUQkhfz8awxVBqfz+rNaXQENUaExEXBgZ7z62tlLiFhRqWALjiF07h4qXG+QNfQ41OOfMDxABtfff1dJ8LcfC8Mz94/Tqgdll+3hm2XF8H0WEXLVIxcjBY+jr2mDqyJyBVeu2hgqRTcerodE=
addons:
  apt:
    packages:
    - lftp
    - tree
    - ruby-sass
    - ruby-compass
before_install:
- openssl aes-256-cbc -K $encrypted_2f4b7b8a1cd1_key -iv $encrypted_2f4b7b8a1cd1_iv
  -in encryptedfiles.tar.enc -out encryptedfiles.tar -d
- bash _scripts/install.sh
script:
- bash _scripts/build.sh
after_success:
- bash _scripts/deploy.sh
